arquillian/ike-prow-plugins

plugin/plugin_init.go, plugin/pr-sanitizer/main.go, plugin/test-keeper/main.go
There was a lot of duplications in the main functions of the plugins - I moved it to a separated function in a separated file.
If I used a wrong abstraction, approach, file/function names or the place for the file, then just tell me. My main problem is that I'm trying to write Java in Go - I need to learn the Go-way properly.
=> chore: moved the common plugin logic from mains to separated function

.travis.yml, Makefile, README.adoc, plugin/plugin_init.go, plugin/pr-sanitizer/main.go, plugin/server/server.go, plugin/test-keeper/plugin/event_handler.go
- sets up `gometalinter` as part of `make build` target 
- configures travis to install linter
- fixes errors identified by the linter
Fixes #17
=> chore(#17): introduces gometalinter

plugin/test-keeper/plugin/test_matcher.go
They matched the correct files, but some "or statements" were redundant and in the Java regex was wrongly copy-pasted optional suffix
=> chore: removes redundant "or statements" from matchers regex

docs/test-keeper.adoc, glide.lock, pkg/github/raw_file_service.go, pkg/internal/test/gomega_matchers.go, pkg/internal/test/test_doubles.go, pkg/plugin/comment_service.go, pkg/plugin/comment_service_test.go, pkg/plugin/config/config_loader.go, pkg/plugin/config/config_loader_test.go, pkg/plugin/plugin_suite_test.go, pkg/plugin/test-keeper/plugin/comment_message.go, pkg/plugin/test-keeper/plugin/comment_message_test.go, pkg/plugin/test-keeper/plugin/configuration.go, pkg/plugin/test-keeper/plugin/configuration_test.go, pkg/plugin/test-keeper/plugin/event_handler.go, pkg/plugin/test-keeper/plugin/event_handler_gh_test.go, pkg/plugin/test-keeper/plugin/test_checker.go, pkg/plugin/test-keeper/plugin/test_fixtures/github_calls/prs/with_tests/test-keeper.yml, pkg/plugin/test_fixtures/github_calls/prs/comments_with_tests_keeper_message.json, pkg/plugin/work-in-progress/plugin/event_handler_gh_test.go, pkg/scm/types.go, pkg/utils/url.go
Before it adds a comment it checks all present comments in the issue/pull-request. 
* If no comment with main plugins title "Ike Plugins" is found, then it adds a new comment with the main title, assignee mention, the test-keeper plugin title and the plugin commentMsg. 
* If a comment with the main title is found but missing the test-keeper plugin title, then it modifies the comment by adding the plugin title with the comment message. 
* If everything is present already, then it does nothing.
Comment message is constructed based on the fact if a configuration is present. 
* If a config file is not present, then it shows default comment referencing to project documentation. 
* If config is present but missing custom comment message there then it shows default with reference to the config …
=> feat(#37): comments on PR when no tests are included

pkg/github/status_service.go, pkg/github/types.go, pkg/plugin/server/server.go, pkg/plugin/test-keeper/plugin/event_handler_gh_test.go, pkg/plugin/work-in-progress/plugin/event_handler_gh_test.go
- adds repo and sender to logging context
- unifies status values by using `const`
Fixes #48
=> feat(#48): adds repository and sender to logging context

README.adoc, docs/sentry.adoc, glide.lock, glide.yaml, pkg/log/log.go, pkg/log/sentry.go, pkg/plugin/plugin_init.go
This PR adds a section about Sentry integration to the documentation.
* locks `raven-go` client
* externalizes logrus and sentry setup to `log` package
=> docs: introduces Sentry section to documentation

.gitignore, pkg/github/github_suite_test.go, pkg/internal/test/ginkgo_custom_reporter.go, pkg/plugin/config/config_suite_test.go, pkg/plugin/test-keeper/plugin/test_keeper_suite_test.go, pkg/plugin/work-in-progress/plugin/work_in_progress_suite_test.go
Configures JUnit reporting for Ginkgo Tests to produce JUnit reports as build artifacts in a format understood by CI servers. 
Fixes: #21
=> feat(#21): configures JUnit reporting for Ginkgo tests.

Makefile
I'm not sure if it is really a bug or just my misunderstanding. After this commit https://github.com/arquillian/ike-prow-plugins/commit/da7a3221d4affdb8984e8c2b8a056dd4af75d16f I'm not able to activate the plugins for my testing repo (using the default setup as I had been used to).
I guess that it was a typo, but I'm not 100% sure, so that's why I'm creating PR :-)
=> fix: use plugins.yaml as the default config file for activating plugins for repositories

glide.lock, pkg/github/client.go, pkg/github/client_test.go, pkg/github/comment_service.go, pkg/github/comment_service_test.go, pkg/github/config_loader.go, pkg/github/status_service.go, pkg/github/status_service_test.go, pkg/http/retry.go, pkg/http/url.go, pkg/internal/test/test_doubles.go, pkg/plugin/plugin_init.go, pkg/plugin/pr-sanitizer/main.go, pkg/plugin/test-keeper/main.go, pkg/plugin/test-keeper/plugin/comment_message.go, pkg/plugin/test-keeper/plugin/event_handler.go, pkg/plugin/test-keeper/plugin/event_handler_gh_test.go, pkg/plugin/work-in-progress/main.go, pkg/plugin/work-in-progress/plugin/event_handler.go, pkg/plugin/work-in-progress/plugin/event_handler_gh_test.go, pkg/plugin/work-in-progress/plugin/event_handler_unit_test.go, pkg/utils/retry.go
* introduced `Client` in `github` package that invokes real GH client
* if response returned from GH has status code >= 404, then it resends the request again - maximal number of attempts is 3
* this new client is used in all plugins instead of the original one because:
* we can alter everything at once - the number of retries and also which requests is the resend logic applied on - currently on all of them
* it will make easier any additional types of scm clients introduced in future
* it decreases the number of parameters
fixes: #75
=> feat(#75): resends GH requests when response code is >= 404

.travis.yml
otherwise, it is not possible to build it from forked repository. The reason is that Travis sets the path to the project using my user account: https://travis-ci.org/MatousJobanek/ike-prow-plugins/builds/361170004#L486
=> fix: sets import path to the ike project specificaly

pkg/http/http_suite_test.go, pkg/http/retry.go, pkg/http/retry_test.go, pkg/plugin/test-keeper/plugin/event_handler_gh_test.go, pkg/utils/retry.go
* there was a bug that when the response returned an error and the exit code was lower than 404, then it didn't return the error.
* another bug was in exit code formatting:
`return errors.New("Server responded with error " + string(response.StatusCode))`
as a result, the output contained:
`1. [Server responded with error Ɣ]`
* I added also test cases for it
Fixes: #87
=> fix(#87): retry function exits when response's exit code is < 404 and returns error that is not nil

Makefile, cluster/hook-template.yaml, glide.lock, glide.yaml
- updates hook service to latest release
- makes host name parametrized with empty default to rely on autogenerated route
=> chore: updates prow hook service

cluster/osio-plugins.yaml
The assign plugin assigns or requests reviews from users. Specific users can be assigned with the command `/assign @user1` or have reviews requested of them with the command `/cc @user1`. If no user is specified the commands default to targeting the user who created the command. Assignments and requested reviews can be removed in the same way that they are added by prefixing the commands with 'un'.
=> feat: adds built-in assign plugin to this repo

pkg/command/cmd_executor.go, pkg/command/cmd_executor_test.go, pkg/command/permission_service.go, pkg/command/permission_service_test.go, pkg/plugin/test-keeper/event_handler_gh_test.go, pkg/utils/strings.go
- removed roles of the user as this could be perceived as leaking sensitive repo information
- disabled logging deletion of the comment - if you don't have rights to invoke it you will be informed and when you delete it won't really give you more information
- minor rewording of the comment itself:
> Hey @bartoszmajsak-test! It seems you tried to trigger `/ok-without-tests` command, but this will not have any effect due to insufficient permission. You have to be admin or requested reviewer, but not pull request creator for this command to take an effect.
=> fix: rewords comments and disable deletion comment

pkg/assets/config/test-keeper.yaml
Ignoring `dep` files, `.dockerignore` and supporting different names for the `docker-compose` files (eg: `docker-compose.dev.yml` or `docker-compose.macos.yml` if there are specificities per host/env in a project.
=> feat: adds more exclusion patterns

pkg/command/permission_service.go, pkg/command/permission_service_test.go, pkg/github/client.go, pkg/plugin/test-keeper/comment_cmd.go, pkg/plugin/test-keeper/event_handler_gh_test.go
* enables bypassing of the test-keeper check to the users who approved the PR - this is retrieved from https://developer.github.com/v3/pulls/reviews/#list-reviews-on-a-pull-request and filtered by
`state == "APPROVED"`
Fixes: #118
=> fix(#118): pr approver can also bypass test-keeper check

Makefile, pkg/assets/config/test-keeper.yaml, pkg/plugin/test-keeper/matchers_test.go
In addition makes `test` target dependent on the `compile-only` so we always test against latest code (and generated assets).
=> fix: corrects docker patterns and excludes .make directory

cluster/hook-template.yaml
Adds liveliness and readiness to the external hook service. The probes listen to `/` end-point [exposed by the service for health checks.](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/hook/main.go#L210)
=> feat(#129): adds liveliness and readiness probes to the hook service.

.make/Makefile.build, .make/Makefile.deploy.prow, .make/Makefile.docker.build, Dockerfile.builder, Makefile, cico_build_deploy.sh, cico_setup.sh, cluster/hook-template.yaml, cluster/ike-prow-template.yaml, glide.lock, prow_version.sh
* added a new cico script `cico_build_deploy.sh` that deploys images to devshift
* add new targets in `Makefile.deploy.prow` to encapsulate actions that compile binary, build images and push to the registry (without processing the template)
* every image version is tagged - adds the possibility of using `latest` tag
* `latest` tag is used as default one in templates
* fixed dockerfile - added missing environments
* extracted logic that retrieves prow version to separated script so I can use it in the cico script as well
Fixes: #97
=> chore(#97): adds centos-ci script that deploys images to devshift

pkg/assets/config/test-keeper.yaml
Configuration file can be `codecov.yml` or `.codecov.yml` as described in https://docs.codecov.io/docs/codecov-yaml#section-repository-yaml
=> Ignore codecov.io config file

.make/Makefile.openshift, cluster/hook-template.yaml, cluster/ike-prow-template.yaml
This is necessary to determine what deployment do the configMaps and secrets
belong to.
=> Rename config maps and secrets

pkg/plugin/work-in-progress/event_handler.go
=> fix(#160): wip plugin handles also synchronize PR action

pkg/github/service/config_loader.go, pkg/plugin/test-keeper/event_handler_gh_test.go
base config always contains plugin name as it is nothing that depends on the loaded config info.
Fixes: #165
=> fix(#165): base config always contains plugin name

pkg/github/service/config_loader.go, pkg/github/service/raw_file_service.go, pkg/plugin/test-keeper/configuration_gh_test.go
* uses blob in config link when redirects to github.com endpoint. For the raw file link, the blob is not needed
Fixes: #172
=> fix(#172): uses blob in config link when redirects to github.com

pkg/plugin/test-keeper/event_handler.go
This is refactoring change - I've noticed it when I was going through the code, that we can get rid of the helper method and use pr loader constructor that takes an already loaded PR
=> chore: use pr loader constuctor instead of helper method

pkg/github/client/pagination_checker.go, pkg/github/client/pagination_checker_test.go, pkg/github/client/rate_limit_watcher.go, pkg/github/client/rate_limit_watcher_test.go, pkg/github/client/retry_wrapper_test.go, pkg/internal/test/test_doubles.go
in the case of pagination checker as well as the rate limit watcher, there was forgotten to execute the inner(earlier) around function. As a side effect, the retry function doesn't work.
So I added the execution of the inner around function and modified the tests to verify the whole combination of the around functions
Fixes: #194
=> fix(#194): every around function execute also inner(earlier) around function

glide.lock, pkg/internal/test/test_doubles.go, pkg/plugin/pr-sanitizer/event_handler.go, pkg/plugin/pr-sanitizer/event_handler_gh_test.go, pkg/plugin/test-keeper/event_handler.go, pkg/plugin/test-keeper/event_handler_gh_test.go, pkg/plugin/test-keeper/metrics_test.go, pkg/plugin/work-in-progress/event_handler.go, pkg/plugin/work-in-progress/event_handler_gh_test.go, pkg/server/metrics_test.go, pkg/server/server.go, plugins.yaml
This PR refactors Handler interface and related logic in plugins by replacing the existing single method by introducing 2 methods to minimize the code duplication:
```
HandlePullRequestEvent(log log.Logger, event *gogh.PullRequestEvent) error
HandleIssueCommentEvent(log log.Logger, event *gogh.IssueCommentEvent) error
```
Fixes: #197
=> refactor(#197): event handler interface to abstract common logic.

Gopkg.lock, pkg/status/status_service_suite_test.go
The missing test suite was causing the following warning:
```
testing: warning: no tests to run
Found no test suites, did you forget to run "ginkgo bootstrap"?
``` 
Fixes #214
=> fix(#214): add missing test suite for status service.

Gopkg.lock, Gopkg.toml, pkg/command/permission_types.go, pkg/utils/secrets.go
Current build is borked due to https://github.com/golang/dep/issues/1799 issue. This PR brings a workaround locking `fsnotify` to certain version.
Fixes #224
=> fix(dep): fixes godep issue while resolving transitive fsnotify

pkg/utils/url.go
Currently, build is failing at static analysis. See build logs https://ci.centos.org/job/devtools-ike-prow-plugins/155/console.
Fixes: #236
=> fix(#236): use http client with timeout as 10s

cluster/osio-plugins.yaml
Add fabric8-build-service, and since I am supposed to be providing a PR that has a length which is greater of a zero then here I am babbling. 
In short and yet very long description, I am adding the `fabric8-build-service` repository from the `fabric8-service` orgnasiation to the `plugins.yaml` so we can have great testing.
How wonderful is that? Is this description helped to better a better understanding of the title of this PR? One may never said!
Here is a bit of usefulness tho! The URL of the repo : 
https://github.com/fabric8-services/fabric8-build-service
although that's probably something you could have get from the yaml file change,
anyway, enjoy your day and thanks fo reading! 
Fixes: #234
=> feat: add fabric8-build-service

cluster/osio-plugins.yaml
This adds fabric8-webhook  from `fabric8-service` orgnasiation to the `osio-plugins.yaml` to enable testing via prow.
Also, correct the name of fabric8-build service name.
Fixes: https://github.com/fabric8-services/fabric8-webhook/issues/3
=> feat: add fabric8-webhook service to the list

cluster/osio-plugins.yaml
The launcher-backend repository was renamed to launcher-application, and therefore ike-prow needs to be updated to continue working
Closes #293
=> fix(#293): repository launcher-backend renamed to launcher-application
